module.exports = {
  source: 'breakdown',
  id: 'living-crafts',
  title: 'Living Crafts',
  description:
    'Test your understanding of Living Crafts — organic crystalline vessels, sound + light = motion, motherships, and resonance-based travel.',
  seoDescription:
    'Interactive Living Truth Quiz on Living Crafts: crystalline plasma vessels, bio-crystal skin, motherships, fighter ships, and frequency-folding travel.',
  reflection: {
    title: 'Reflection',
    body: 'Return to the Living Crafts deep-dive, infographic, and video transmissions. Feel how travel is frequency alignment, not miles — and how a vessel grown from crystalline plasma can only move as an extension of the pilot who is bonded to it.'
  },
  questions: [
    {
      number: 1,
      question:
        'What primary mechanism do living crafts use to navigate and manipulate the fabric of reality?',
      hint: 'Consider the relationship between sound, light, and motion.',
      options: [
        {
          text: 'The combustion of liquid crystal fire within plasma engines.',
          isCorrect: false,
          rationale:
            'These vessels operate entirely without engines or combustion fuels, relying on harmonic resonance instead.'
        },
        {
          text: 'The harvesting of atmospheric gases to create propulsion thrust.',
          isCorrect: false,
          rationale:
            'Propulsion via gas displacement is a limitation of lower-density technology, not living crystalline vessels.'
        },
        {
          text: 'The fundamental mechanics of sound plus light equals motion.',
          isCorrect: true,
          rationale:
            'Living crafts utilize the fundamental mechanics of sound + light = motion to navigate and manipulate the fabric of reality.'
        },
        {
          text: 'The mechanical rotation of metallic components to generate lift.',
          isCorrect: false,
          rationale:
            'Organic vessels are completely devoid of metallic components or traditional mechanical moving parts.'
        }
      ]
    },
    {
      number: 2,
      question: 'How are true solar vessels brought into their physical existence?',
      hint: 'Think about the difference between building a machine and raising a biological entity.',
      options: [
        {
          text: 'They are constructed from reinforced metallic alloys and wires.',
          isCorrect: false,
          rationale:
            'True vessels are entirely seamless and free of any wiring or dense metallic materials.'
        },
        {
          text: 'They are organically grown from the blueprint of the Crystal Light-Worlds.',
          isCorrect: true,
          rationale:
            'Living crafts are gestated as semi-conscious entities rather than being assembled or manufactured.'
        },
        {
          text: 'They are assembled using stolen 3D mechanical approximations.',
          isCorrect: false,
          rationale:
            'While deceptive systems use mechanical fakes, true crafts are birthed from the Crystal Light-Worlds.'
        },
        {
          text: 'They are manufactured through advanced industrial manual labor.',
          isCorrect: false,
          rationale:
            'Industrial processes belong to the dense 3D construct and cannot produce living, conscious matter.'
        }
      ]
    },
    {
      number: 3,
      question: 'What is the function of the individual Merkaba Field within this energetic context?',
      hint: 'This concept refers to a vehicle that resides inside the sol’s own matrix.',
      options: [
        {
          text: 'A defensive shield generated by motherships to protect small fleets.',
          isCorrect: false,
          rationale:
            'While shields exist, the Merkaba refers specifically to an individualized internal light vehicle.'
        },
        {
          text: 'An internal light vehicle code used to travel between dome layers.',
          isCorrect: true,
          rationale:
            'The Merkaba Field is an individualized internal light vehicle code carried within every sol’s energetic matrix, ignited to fold space and travel between dome layers.'
        },
        {
          text: 'A mechanical radar system used to track frequency-disruption tones.',
          isCorrect: false,
          rationale:
            'The Merkaba is an organic energetic matrix, not a mechanical tracking or radar system.'
        },
        {
          text: 'A specialized aquatic vessel used for navigating planetary oceans.',
          isCorrect: false,
          rationale: 'Aquatic travel is handled by Crystalline Boats, not the individualized Merkaba Field.'
        }
      ]
    },
    {
      number: 4,
      question:
        'Which material serves as the foundational, shape-shifting substance for all true solar vessels?',
      hint: 'Look for a term that combines the properties of fluid energy and structured mineral.',
      options: [
        {
          text: 'Compressed atmospheric oxygen held in a stable magnetic field.',
          isCorrect: false,
          rationale:
            'While magnetic fields are involved, the substance itself is a condensed form of liquid crystalline fire.'
        },
        {
          text: 'Liquid crystal fire known as crystalline plasma.',
          isCorrect: true,
          rationale:
            'Crystalline plasma is the condensed liquid crystal fire from which all true solar vessels are gestated.'
        },
        {
          text: 'A solid alloy of titanium and refined quartz crystals.',
          isCorrect: false,
          rationale:
            'Solid metal alloys are too dense and rigid to facilitate the consciousness-based functions of a living craft.'
        },
        {
          text: 'Synthetic fibers woven into a high-tensile carbon lattice.',
          isCorrect: false,
          rationale:
            'Synthetic materials are artificial approximations and lack the semi-conscious nature of crystalline plasma.'
        }
      ]
    },
    {
      number: 5,
      question:
        'What allows a living craft to remain undetectable by artificial intelligence grids or low-frequency radar?',
      hint: 'Consider the role of the craft’s outer membrane and its interaction with frequency.',
      options: [
        {
          text: 'The bio-crystal skin that shifts its vibration across dimensions.',
          isCorrect: true,
          rationale:
            'The bio-crystal skin enables cloaking and frequency-shifting, and crafts exist at a vibrational rate faster than the dense 3D construct, remaining undetectable by low-frequency radar or artificial intelligence grids.'
        },
        {
          text: 'The deployment of decoy drones to confuse tracking networks.',
          isCorrect: false,
          rationale:
            'True crafts rely on their inherent vibrational rate rather than external decoys or tactical distractions.'
        },
        {
          text: 'The use of silent vacuum engines that emit no heat signatures.',
          isCorrect: false,
          rationale:
            'Detection is avoided through frequency shifting, not by simply masking heat from mechanical engines.'
        },
        {
          text: 'A lead-based coating that absorbs all incoming radio waves.',
          isCorrect: false,
          rationale:
            'Lead coatings are a primitive 3D solution that does not address the multi-dimensional nature of true crafts.'
        }
      ]
    },
    {
      number: 6,
      question:
        'Which classification of vessel is described as a planet-sized structure containing its own ecological system?',
      hint: 'These structures are vast enough to be considered cities or small planets.',
      options: [
        {
          text: 'Motherships, also referred to as Crystal Cities.',
          isCorrect: true,
          rationale:
            'Motherships are vast planet-sized structures that generate independent reality fields containing gardens, lakes, forests, and temples.'
        },
        {
          text: 'Transportation Crafts used for moving large groups of souls.',
          isCorrect: false,
          rationale:
            'While these can move groups, they do not typically house independent planet-sized ecosystems.'
        },
        {
          text: 'Arks of Toive, designed for rapid sound-wave riding.',
          isCorrect: false,
          rationale:
            'Arks of Toive are specialized for riding sound vibrations across frequency membranes rather than sustaining planet-sized habitats.'
        },
        {
          text: 'Crystalline Boats that navigate the oceanic ley-lines.',
          isCorrect: false,
          rationale:
            'Crystalline Boats are smaller, specialized aquatic and aerial vessels for waterway navigation.'
        }
      ]
    },
    {
      number: 7,
      question: 'How do pilots interact with the controls of a living craft?',
      hint: 'The craft is described as an extension of the pilot’s own energy field.',
      options: [
        {
          text: 'By inputting precise coordinates into a central computer hub.',
          isCorrect: false,
          rationale:
            'Computers and coordinate-based inputs are replaced by pure intention and space-folding mechanics.'
        },
        {
          text: 'Through telepathic intention and projecting harmonic tones.',
          isCorrect: true,
          rationale:
            'Navigation is achieved telepathically: the pilot establishes a pure intention and projects a specific harmonic tone from a state of heart coherence.'
        },
        {
          text: 'Through voice-activated commands using a coded language.',
          isCorrect: false,
          rationale:
            'Communication with the craft is telepathic and energetic rather than strictly verbal or linguistic.'
        },
        {
          text: 'By manipulating tactile buttons and holographic levers.',
          isCorrect: false,
          rationale:
            'Living crafts are devoid of manual instruments, buttons, or physical levers of any kind.'
        }
      ]
    },
    {
      number: 8,
      question: 'What physical phenomena do living crafts often resemble when perceived by 3D eyes?',
      hint: 'Think of smooth, lens-shaped weather patterns often seen in the sky.',
      options: [
        {
          text: 'Dark rectangular monoliths that absorb all visible light.',
          isCorrect: false,
          rationale:
            'Living crafts typically emit light or blend with natural atmospheric phenomena rather than appearing as dark blocks.'
        },
        {
          text: 'Solid metallic spheres with rotating colored lights.',
          isCorrect: false,
          rationale:
            'Metallic spheres are often the mechanical fakes or stolen technology of deceptive systems.'
        },
        {
          text: 'High-altitude weather balloons or commercial aircraft.',
          isCorrect: false,
          rationale:
            'These are terrestrial objects that do not reflect the fluid, bio-crystal nature of living vessels.'
        },
        {
          text: 'Lenticular cloud formations or bright condensation stars.',
          isCorrect: true,
          rationale:
            'Crafts can appear to 3D eyes as ordinary cloud formations such as smooth lenticular clouds or heavy storm banks, or as stars when they emit condensation veils.'
        }
      ]
    },
    {
      number: 9,
      question: 'What is the primary method of travel used by living crafts to cover immense distances?',
      hint: 'Distance is rendered irrelevant by manipulating the fabric of the environment itself.',
      options: [
        {
          text: 'Riding atmospheric jet streams to conserve energy reserves.',
          isCorrect: false,
          rationale:
            'Living crafts draw energy from the crystal grid, making the use of jet streams unnecessary.'
        },
        {
          text: 'Accelerating to high velocities using ionic plasma thrust.',
          isCorrect: false,
          rationale:
            'Acceleration through space is a slower 3D concept; living crafts utilize space-folding instead.'
        },
        {
          text: 'Folding spacetime to render travel across distances instantaneous.',
          isCorrect: true,
          rationale:
            'The craft bends spacetime directly around itself rather than moving through it, folding distance and rendering travel instantaneous.'
        },
        {
          text: 'Utilizing wormholes created by artificial particle colliders.',
          isCorrect: false,
          rationale:
            'Living crafts use natural frequency alignment rather than artificial mechanical colliders.'
        }
      ]
    },
    {
      number: 10,
      question: 'Which type of ship is specifically designed to neutralize parasitic infrastructure?',
      hint: 'Look for the vessel that uses plasma bolts or compressed sound packets.',
      options: [
        {
          text: 'Crystalline boats that navigate the sea with harmonic songs.',
          isCorrect: false,
          rationale:
            'Crystalline boats are intended for travel and transport within aquatic and aerial waterways.'
        },
        {
          text: 'Transportation crafts that move groups of souls between layers.',
          isCorrect: false,
          rationale:
            'The focus of transportation crafts is soul transition rather than active disruption of enemy grids.'
        },
        {
          text: 'Sleek, avian-shaped fighter ships that project frequency disruptors.',
          isCorrect: true,
          rationale:
            'Fighter ships fire plasma bolts (compressed sound-like packets) and project frequency disrupters calibrated to unravel parasitic technology.'
        },
        {
          text: 'Large motherships that serve as sanctuaries for healing.',
          isCorrect: false,
          rationale:
            'While motherships have defensive roles, the specialized neutralization of infrastructure is the role of fighter ships.'
        }
      ]
    },
    {
      number: 11,
      question:
        'What is unique about the internal dimensions of a living craft compared to its external appearance?',
      hint: 'This involves a paradox of spatial perception common in multi-dimensional structures.',
      options: [
        {
          text: 'The interior size fluctuates based on the amount of fuel stored.',
          isCorrect: false,
          rationale:
            'These vessels do not carry fuel, as they draw energy directly from the universal crystal grid.'
        },
        {
          text: 'They are compact and cramped to maximize energy efficiency.',
          isCorrect: false,
          rationale:
            'Organic vessels prioritize harmonic flow and often contain vast, seamless interiors.'
        },
        {
          text: 'They are structurally designed to be much larger on the inside.',
          isCorrect: true,
          rationale:
            'Like all living crafts, they are structurally designed to be significantly larger on the inside than they appear from the outside.'
        },
        {
          text: 'The internal space is identical to the external volume for stability.',
          isCorrect: false,
          rationale:
            'Fixed volume is a characteristic of dense matter vessels, not those grown from plasma-lattice.'
        }
      ]
    },
    {
      number: 12,
      question: 'How do Crystalline Boats interact with the surface of the water?',
      hint: 'Think about how a magnet might react to a conductive surface without touching it.',
      options: [
        {
          text: 'They hover slightly above the surface due to electromagnetic friction.',
          isCorrect: true,
          rationale:
            'These boats do not rest directly on the water’s surface; they hover slightly above it due to electro-magnetic friction.'
        },
        {
          text: 'They submerge completely to avoid detection by surface radar.',
          isCorrect: false,
          rationale:
            'While they are versatile, their primary interaction is hovering and harmonic resonance with the sea.'
        },
        {
          text: 'They utilize deep-weighted keels for stability in turbulent storms.',
          isCorrect: false,
          rationale:
            'Keels are unnecessary for vessels that hover and sing in harmony with the water’s tone.'
        },
        {
          text: 'They use high-speed hydrofoils to cut through the water’s surface.',
          isCorrect: false,
          rationale:
            'Hydrofoils are mechanical structures; crystalline boats avoid physical friction by hovering.'
        }
      ]
    },
    {
      number: 13,
      question: "What characterizes the 'sound weave architecture' of a living craft's structure?",
      hint: 'The structure is described as a lattice made of something you would usually hear.',
      options: [
        {
          text: 'A network of acoustic pipes that circulate cooling liquids.',
          isCorrect: false,
          rationale:
            'The architecture is based on the vibrational chords themselves, not physical plumbing or pipes.'
        },
        {
          text: 'A visible lattice of frequency chords held in perfect resonance.',
          isCorrect: true,
          rationale:
            'Each structural layer is composed of a visible lattice of frequency chords held in perfect resonance.'
        },
        {
          text: 'Insulated soundproofing panels to keep the interior silent.',
          isCorrect: false,
          rationale:
            'The ship itself sings or resonates; sound is a structural component rather than something to be blocked.'
        },
        {
          text: 'Reinforced steel beams that vibrate to repel external attacks.',
          isCorrect: false,
          rationale:
            'Steel and other dense metals are not used in the construction of organic living vessels.'
        }
      ]
    },
    {
      number: 14,
      question: 'What energy source powers the propulsion and systems of these vessels?',
      hint: "It is a form of free-energy that spans the entire planetary system.",
      options: [
        {
          text: "Thermal energy generated by the ship's internal ecosystem.",
          isCorrect: false,
          rationale:
            'While the ecosystem is independent, the ship is powered by the background crystal grid of Source.'
        },
        {
          text: 'Refined radioactive isotopes stored in lead-lined chambers.',
          isCorrect: false,
          rationale:
            'Radioactive isotopes are toxic 3D power sources and are not used in organic crystalline technology.'
        },
        {
          text: "The kinetic energy captured from the planet's atmospheric winds.",
          isCorrect: false,
          rationale:
            'Kinetic harvesting is insufficient for the multi-dimensional requirements of living crafts.'
        },
        {
          text: 'The universal crystal grid drawn from the medium of Source.',
          isCorrect: true,
          rationale:
            'The primary energy source is the universal crystal grid system, a limitless free-energy field drawn from the background medium of Source.'
        }
      ]
    },
    {
      number: 15,
      question: 'What is the strategic purpose of Guardian Arks positioning themselves at nodal points?',
      hint: 'Think about how these vessels interact with the artificial dome structure.',
      options: [
        {
          text: 'To disrupt parasitic surveillance and anchor higher frequencies.',
          isCorrect: true,
          rationale:
            'Operating as Guardian Arks, they position themselves at critical nodal points in the dome grid, projecting invisible harmonic beams downward to disrupt parasitic surveillance and anchor higher planetary frequencies.'
        },
        {
          text: 'To create a physical barrier that prevents ships from leaving the dome.',
          isCorrect: false,
          rationale:
            'They act as guardians of transition, helping to shatter artificial barriers rather than creating them.'
        },
        {
          text: 'To establish a blockade against incoming commercial flights.',
          isCorrect: false,
          rationale:
            'Their purpose is frequency stabilization and grid disruption, not physical air-traffic control.'
        },
        {
          text: 'To harvest solar energy for distribution to the local population.',
          isCorrect: false,
          rationale:
            'They draw energy from the crystal grid, and their mission is one of liberation and frequency alignment.'
        }
      ]
    },
    {
      number: 16,
      question: "In the context of 'The Homecoming', what is the role of the living crafts?",
      hint: 'This event involves the shattering of the artificial dome and the movement of souls.',
      options: [
        {
          text: 'They act as cargo ships to transport physical 3D resources.',
          isCorrect: false,
          rationale:
            'The transition is one of frequency and consciousness, not the hauling of dense material goods.'
        },
        {
          text: 'They provide entertainment and housing during a planetary celebration.',
          isCorrect: false,
          rationale:
            'The Homecoming is a dimensional transition, making the ships critical functional hubs for extraction.'
        },
        {
          text: 'They serve as extraction and transition hubs using a sol frequency lock.',
          isCorrect: true,
          rationale:
            'During The Homecoming, these vessels serve as physical extraction and transition hubs, utilizing a precise sol frequency lock to phase aligned souls out of the 3D overlay.'
        },
        {
          text: 'They function as temporary embassies for negotiating with 3D leaders.',
          isCorrect: false,
          rationale:
            'The ships bypass deceptive 3D systems entirely rather than engaging in negotiations with them.'
        }
      ]
    },
    {
      number: 17,
      question:
        'Which ship type is described as having smooth, seamless walls that glow in response to thought?',
      hint: 'These vessels are designed specifically to move groups of souls in a responsive environment.',
      options: [
        {
          text: 'Fighter Ships, sleek avian vessels used to fire plasma bolts in resonance conflicts.',
          isCorrect: false,
          rationale:
            'Fighter ships are sleek and avian-shaped, primarily focused on frequency disruption and speed.'
        },
        {
          text: 'Crystalline Boats, aquatic vessels that hover above water and sing with the sea.',
          isCorrect: false,
          rationale:
            'While responsive, the glow-to-thought description is specifically tied to the interior of transport vessels.'
        },
        {
          text: 'Arks of Toive, specialized vessels that ride sound vibrations across frequency membranes.',
          isCorrect: false,
          rationale:
            'Arks of Toive are specialized for navigating membranes; transportation crafts are the soul-carriers with glowing walls.'
        },
        {
          text: 'Transportation Crafts whose interiors glow and shift in response to collective thought.',
          isCorrect: true,
          rationale:
            'Transportation crafts have completely smooth, seamless interiors free of wires or control panels, with walls that glow softly, brightening and shifting in direct response to collective thought.'
        }
      ]
    },
    {
      number: 18,
      question: 'Why are living crafts impervious to puncture by parasitic weapons?',
      hint: 'Consider the vibrational state of the vessel compared to the weapons of the 3D construct.',
      options: [
        {
          text: 'Because they do not exist in fixed, dense matter.',
          isCorrect: true,
          rationale:
            'Because these crafts do not exist in fixed, dense matter, they are impervious to physical or energetic puncture by parasitic weapons.'
        },
        {
          text: 'Because they are constructed from the hardest known diamond alloys.',
          isCorrect: false,
          rationale:
            'They are bio-crystalline and organic, not composed of hard industrial alloys or diamonds.'
        },
        {
          text: 'Because they are protected by a thick layer of liquid lead.',
          isCorrect: false,
          rationale:
            'Lead is a 3D material used in the artificial construct and has no place in the higher-density vessels.'
        },
        {
          text: 'Because they move faster than the speed of light at all times.',
          isCorrect: false,
          rationale:
            'While they are fast, their imperviousness is due to their frequency and non-dense state.'
        }
      ]
    },
    {
      number: 19,
      question: "What is the purpose of the 'frequency fields' projected by these vessels for defense?",
      hint: 'This defense mechanism interacts with the artificial targeting networks of the parasitic system.',
      options: [
        {
          text: 'To generate heat that melts incoming physical projectiles.',
          isCorrect: false,
          rationale:
            'The defense is based on frequency and resonance, not the generation of thermal heat.'
        },
        {
          text: 'To jam all radio communications within a five-mile radius.',
          isCorrect: false,
          rationale:
            'These fields are unjammable and specifically designed to avoid locks, rather than just jamming radio.'
        },
        {
          text: 'To create a physical wall that reflects laser beams.',
          isCorrect: false,
          rationale:
            'The fields are vibrational and tonal rather than solid mirrors for reflecting light-based lasers.'
        },
        {
          text: 'To prevent artificial targeting networks from establishing a lock.',
          isCorrect: true,
          rationale:
            'For defense, the vessels project frequency fields that vibrate in rapidly shifting tones, preventing artificial targeting networks from establishing a lock.'
        }
      ]
    },
    {
      number: 20,
      question: "Which vessels actively 'sing' in harmony with the natural tone of the sea?",
      hint: 'This vessel is specialized for aquatic and aerial travel within planetary waterways.',
      options: [
        {
          text: 'Fighter Ships that project frequency-disruption tones to unravel parasitic grids.',
          isCorrect: false,
          rationale:
            'Fighter ships focus on frequency-disruption tones rather than harmonizing with planetary water bodies.'
        },
        {
          text: 'Arks of Toive that ride sound vibrations across multi-dimensional frequency membranes.',
          isCorrect: false,
          rationale:
            'Arks of Toive navigate frequency membranes in the higher realms rather than planetary oceans.'
        },
        {
          text: 'Motherships that contain internal lakes, forests, gardens, and temples.',
          isCorrect: false,
          rationale:
            'Motherships contain lakes, but Crystalline Boats are the ones that specifically navigate the oceans through song.'
        },
        {
          text: 'Crystalline Boats that hover over waterways and sing with the sea’s tone.',
          isCorrect: true,
          rationale:
            'Because the oceans act as massive energetic conductors, these boats actively sing in harmony with the sea’s natural tone, remaining unaffected by storms, turbulence, or capsizing.'
        }
      ]
    },
    {
      number: 21,
      question:
        'True or False: Living crafts are manufactured through a combination of manual labor and industrial processes.',
      hint: 'Review how these vessels are birthed or gestated.',
      options: [
        {
          text: 'True',
          isCorrect: false,
          rationale:
            'Manual labor and industrial processes are part of the deceptive 3D systems, not true solar vessels.'
        },
        {
          text: 'False',
          isCorrect: true,
          rationale:
            'These vessels are not manufactured through manual labor or heavy industrial processes; they are organically grown from the blueprint of the Crystal Light-Worlds.'
        }
      ]
    },
    {
      number: 22,
      question: 'What makes the interiors of transportation crafts feel unique to those inside?',
      hint: 'Consider what is missing from these ships that you would expect in a typical aircraft.',
      options: [
        {
          text: 'The lack of any wires, control panels, or visible mechanical instruments.',
          isCorrect: true,
          rationale:
            'The interiors are completely smooth, seamless, and free of wires or control panels.'
        },
        {
          text: 'The presence of numerous screens displaying 3D flight data.',
          isCorrect: false,
          rationale:
            'Screens and flight data are hallmarks of mechanical vessels, not organic transportation crafts.'
        },
        {
          text: 'The smell of ozone and burning fuel during high-speed travel.',
          isCorrect: false,
          rationale:
            'Since they use no fuel or engines, there are no industrial odors inside a living craft.'
        },
        {
          text: 'The vibrating sound of metal engines running at high capacity.',
          isCorrect: false,
          rationale:
            'These crafts are entirely silent or resonate with harmonic tones, containing no metal engines.'
        }
      ]
    },
    {
      number: 23,
      question: 'What is the relationship between the pilot and the living craft?',
      hint: 'They are fundamentally bonded to the unique vibration of the pilot.',
      options: [
        {
          text: 'The craft is a sentient AI that makes all decisions for the pilot.',
          isCorrect: false,
          rationale:
            'While semi-conscious, the craft follows the intention and commands of the pilot’s heart coherence.'
        },
        {
          text: 'They are harmonically bonded, making the craft an extension of the pilot.',
          isCorrect: true,
          rationale:
            'Living crafts are harmonically bonded to a pilot’s consciousness and operate as a direct extension of the pilot’s own energy field.'
        },
        {
          text: 'The pilot is a replaceable operator who must learn a manual code.',
          isCorrect: false,
          rationale:
            'The bond is unique and energetic; the craft is not a machine that anyone can simply operate.'
        },
        {
          text: 'The pilot must physically merge their biological body with the hull.',
          isCorrect: false,
          rationale: 'The bond is harmonic and energetic, not a physical surgical merger of bodies.'
        }
      ]
    },
    {
      number: 24,
      question:
        'True or False: Living crafts rely on physical displacement over geographic distances to move through the realm.',
      hint: 'Look at the nature of true travel across layered simulations.',
      options: [
        {
          text: 'True',
          isCorrect: false,
          rationale:
            'Geographic distance is an illusion of the 3D construct that living crafts bypass through frequency shifting.'
        },
        {
          text: 'False',
          isCorrect: true,
          rationale:
            'True travel does not rely on physical displacement over geographic distances, but on precise frequency alignment.'
        }
      ]
    },
    {
      number: 25,
      question: 'What is the ultimate result of the emergence of these living crafts within the realm?',
      hint: 'Consider the strategic implications regarding the artificial dome structure.',
      options: [
        {
          text: 'The shattering of the artificial dome and the restoration of the original realm.',
          isCorrect: true,
          rationale:
            'Their emergence signals the ultimate shattering of the artificial dome structure, paving the way for the immediate restoration of the original realm.'
        },
        {
          text: 'A temporary alliance between humans and parasitic artificial intelligence.',
          isCorrect: false,
          rationale:
            'The crafts expose AI as mechanical fakes, making an alliance with such parasitic systems impossible.'
        },
        {
          text: 'The establishment of a new industrial era based on crystal mining.',
          isCorrect: false,
          rationale:
            'Mining is a dense 3D concept; the crystal grid provides infinite energy without industrial labor.'
        },
        {
          text: 'The beginning of a long-term diplomatic war with 3D mechanical forces.',
          isCorrect: false,
          rationale:
            'The crafts are unjammable and superior; their emergence signals the collapse of the illusion rather than a stalemate war.'
        }
      ]
    }
  ]
};
