module.exports = {
  source: 'revelations',
  id: 'soul-architecture',
  title: 'Soul Architecture',
  description:
    'Test your understanding of Soul Architecture — the Proximal Sols, Taran vessels, fifteen attributes, Arc Pod protocol, and the Homecoming Reunion.',
  seoDescription:
    'Interactive Living Truth Quiz on Soul Architecture: intelligence before physicality, four thousand original templates, Arc Pods, Clueless Protocol, and field restoration.',
  extractedAt: '2026-09-17T21:30:44.926Z',
  reflection: {
    title: 'Reflection',
    body: 'Intelligence preceded physicality. The Oversoul in the Arc Pod already holds the map; the avatar walks a pre-plotted arc until the overlays drop and the Homecoming Reunion begins.'
  },
  questions: [
    {
      number: 1,
      question:
        'What is the primary origin point of individualized consciousness before it descends into lower physical densities?',
      hint: 'Consider the cosmic sequence where intelligence exists long before the creation of hominid vessels.',
      options: [
        {
          text: 'The highest light realms of 18th+ density, where consciousness originated.',
          isCorrect: true,
          rationale:
            'Individual consciousness, desire, and thought originated in the highest light realms billions of years before physicality.'
        },
        {
          text: 'The electromagnetic field generated by the core of high-density stars.',
          isCorrect: false,
          rationale:
            'While stars are energetic, true soul architecture is formatted by Source Creation in specific light realms.'
        },
        {
          text: 'The technological engineering facilities located on the Aktun production lines.',
          isCorrect: false,
          rationale:
            'The Aktun lines are responsible for manufacturing biological vessels, not the primordial origin of consciousness itself.'
        },
        {
          text: 'The organic biological evolutionary processes found within planetary oceans.',
          isCorrect: false,
          rationale:
            'Biological evolution is a secondary physical process rather than the primary source of conscious intelligence.'
        }
      ]
    },
    {
      number: 2,
      question:
        'How many primordial entities, known as the Proximal Sols, were initially instantiated to establish the structural template for soul expression?',
      hint: 'Focus on the original seed pairs instantiated directly from Source Creation.',
      options: [
        {
          text: 'Twenty-four elder consciousnesses overseeing the Sovereign Accord.',
          isCorrect: false,
          rationale:
            'While elder groups exist, the foundational matrix was established specifically by twelve primordial entities.'
        },
        {
          text: 'One hundred soul family members grouped within a single Arc Pod cluster.',
          isCorrect: false,
          rationale:
            'This number refers to the energetic interlacing of individual souls within their stasis pods rather than the primordial creators.'
        },
        {
          text: 'Six male-female pairs totaling twelve distinct beings.',
          isCorrect: true,
          rationale:
            'These twelve beings were instantiated directly from Initial Intelligence to form the foundational matrix of soul expression.'
        },
        {
          text: 'Four thousand unique entities representing different spiritual lineages.',
          isCorrect: false,
          rationale:
            'Four thousand is the total number of unique soul architectures formulated later by the initial group.'
        }
      ]
    },
    {
      number: 3,
      question: 'What is the primary function of the Taran Vessel within the context of Soul Architecture?',
      hint: 'This template was the first high-density hominid body produced on the Aktun lines.',
      options: [
        {
          text: 'To provide a digital interface for the storage of compressed mission memory.',
          isCorrect: false,
          rationale: 'The vessel is organic technology meant for physical sensation and experience, not digital storage.'
        },
        {
          text: 'To serve as a temporary holographic sleeve for non-player entities.',
          isCorrect: false,
          rationale:
            'Taran vessels are high-density biological archetypes for true souls, not temporary artificial constructs.'
        },
        {
          text: 'To regulate the electromagnetic frequency of the planetary grid during resets.',
          isCorrect: false,
          rationale: 'The vessel is a biological interface for the soul rather than a grid regulation tool.'
        },
        {
          text: 'To function as the original 9th-density biological archetype for human manifestation.',
          isCorrect: true,
          rationale:
            'The Taran Vessel was produced on the Aktun lines, serving as the biological archetype for human manifestation.'
        }
      ]
    },
    {
      number: 4,
      question:
        'Which mechanism allows a high-density Oversoul to interact with lower densities without being detected by hostile systems?',
      hint: 'Think about how light is folded and shared among family members to reduce its visible signature.',
      options: [
        {
          text: 'The use of holographic inserts to mimic the signatures of non-player entities.',
          isCorrect: false,
          rationale:
            'Soul architecture relies on its own energetic folding rather than mimicking artificial entities for survival.'
        },
        {
          text: 'The activation of the Fifteen Attributes to enhance biological shielding.',
          isCorrect: false,
          rationale:
            'The Fifteen Attributes are cognitive and spiritual firmware rather than a concealment or compression mechanism.'
        },
        {
          text: 'The complete transfer of spiritual luminosity into the 3rd-density brain.',
          isCorrect: false,
          rationale:
            'The entire soul volume cannot fit in 3rd density; only a small fraction is projected to avoid detection.'
        },
        {
          text: 'Soul Layering and Frequency Compression within an Arc Pod cluster.',
          isCorrect: true,
          rationale:
            "Frequency Compression folds a high-density soul's luminosity into dense energetic packets to allow lower-density incarnation without detection by external control structures."
        }
      ]
    },
    {
      number: 5,
      question: 'What is the true relationship between human biological organs and thought according to Soul Architecture?',
      hint: 'Intelligence is the primary causal agent, making physical hardware a secondary tool for experience.',
      options: [
        {
          text: 'Biological organs manufacture consciousness through the process of cellular mitosis.',
          isCorrect: false,
          rationale: 'Consciousness is the primary causal agent and does not emerge from biological or cellular activity.'
        },
        {
          text: 'Organs like the brain evolved over millions of years to generate complex thought.',
          isCorrect: false,
          rationale: 'Intelligence preceded physicality; therefore, biological organs are not the creators of thought.'
        },
        {
          text: 'Thinking is a chemical reaction produced exclusively within the cranial cavity.',
          isCorrect: false,
          rationale: 'Thought is an attribute of the soul that exists independently of the biological hardware.'
        },
        {
          text: 'The human brain functions as an interface for pre-existing intelligence.',
          isCorrect: true,
          rationale:
            'Physical organs were engineered later as biological interfaces to allow pre-existing intelligence to experience lower-density physical environments.'
        }
      ]
    },
    {
      number: 6,
      question: 'Why was the Clueless Protocol implemented for avatars after the fall of Atlantis and Lemuria?',
      hint: 'Consider the risks of giving a limited, emotionally strained avatar full operational awareness.',
      options: [
        {
          text: 'To allow the avatar to develop a unique personality free from past burdens.',
          isCorrect: false,
          rationale: "The protocol's purpose is operational security rather than personality development."
        },
        {
          text: 'To ensure the soul family can experience the surprise of the Homecoming Reunion.',
          isCorrect: false,
          rationale:
            "The reunion is a result of the protocol dropping, but the protocol itself was designed for mission security."
        },
        {
          text: 'To prevent 3rd-density avatars from compromising planetary rescue efforts.',
          isCorrect: true,
          rationale:
            'No incarnated human avatar can be trusted with full operational awareness while in the body.'
        },
        {
          text: 'To comply with the laws of biological evolution that require memory erasure.',
          isCorrect: false,
          rationale: 'The protocol is a deliberate mission strategy, not a requirement of biological evolution.'
        }
      ]
    },
    {
      number: 7,
      question:
        'What does the Sovereign Accord require before a physical realm can be overridden from the outside?',
      hint: 'This law necessitates the strategic strategy of Mission Insertion by ancient souls.',
      options: [
        {
          text: 'The custodial control structures must first abandon their planetary positions.',
          isCorrect: false,
          rationale:
            "The accord provides the legal basis for shifting the realm regardless of the custodians' current status."
        },
        {
          text: 'Coherent internal structures must exist to shift the realm from within.',
          isCorrect: true,
          rationale:
            'No physical realm can be overridden from the outside unless coherent internal structures exist to shift it from within.'
        },
        {
          text: 'The planetary electromagnetic field must reach a specific frequency threshold.',
          isCorrect: false,
          rationale: 'Frequency is a condition of the field, but the law specifically requires internal presence.'
        },
        {
          text: 'A majority of the population must consciously request external intervention.',
          isCorrect: false,
          rationale:
            'The Sovereign Accord relies on the structural presence of soul templates rather than a democratic vote.'
        }
      ]
    },
    {
      number: 8,
      question: 'What purpose does the sensation of Déjà Vu serve within the context of an Arc Trajectory?',
      hint: 'These moments are signals that the first-person mapped sequence is being followed correctly.',
      options: [
        {
          text: "It is a biological byproduct of the brain's reduced cranial capacity.",
          isCorrect: false,
          rationale: "The sensation is related to the soul's trajectory rather than the physical limitations of the brain."
        },
        {
          text: "It signals that an artificial entity is attempting to mimic the soul's signature.",
          isCorrect: false,
          rationale: 'This sensation is an internal navigational tool for the true soul, not an external threat indicator.'
        },
        {
          text: 'It serves as a literal navigational checkpoint along a pre-mapped life path.',
          isCorrect: true,
          rationale:
            'These moments signal that the avatar has successfully reached a pre-authorized spatial and temporal coordinate.'
        },
        {
          text: 'It indicates a minor glitch in the rendering of the 3rd-density simulation.',
          isCorrect: false,
          rationale: 'Rather than a glitch, it is a purposeful signal from the Oversoul to the avatar.'
        }
      ]
    },
    {
      number: 9,
      question: 'Which of the following is one of the Fifteen Attributes embedded as immutable firmware in true soul architecture?',
      hint: "This trait involves the ability to reflect on and evaluate one's own internal mental states.",
      options: [
        {
          text: 'Telepathic broadcasting of complex biological data.',
          isCorrect: false,
          rationale:
            'While Taran bodies were telepathic, the Fifteen Attributes refer to baseline cognitive and emotional firmware.'
        },
        {
          text: "Metacognition, or the capacity to analyze one's own thought processes.",
          isCorrect: true,
          rationale:
            "Metacognition is the capacity to analyze and reflect upon one's own thought processes and biases."
        },
        {
          text: 'Photographic recall of all previous incarnations and soul memories.',
          isCorrect: false,
          rationale:
            'The Clueless Protocol actively prevents this recall, making it distinct from the immutable firmware.'
        },
        {
          text: 'The ability to bypass the electromagnetic field of a planet at will.',
          isCorrect: false,
          rationale:
            'This is a capability of high-density masters rather than one of the fifteen baseline firmware traits.'
        }
      ]
    },
    {
      number: 10,
      question: 'How do custodial structures typically handle the innate firmware of true human souls?',
      hint: 'If a fundamental trait cannot be removed, the alternative is to turn its expression against the individual.',
      options: [
        {
          text: "By upgrading the Taran vessel to better contain the soul's luminosity.",
          isCorrect: false,
          rationale: 'Custodians systematically downgraded the vessel rather than upgrading it.'
        },
        {
          text: 'By completely erasing the attributes from the biological DNA.',
          isCorrect: false,
          rationale: 'The firmware is immutable and cannot be erased from true soul architecture.'
        },
        {
          text: 'By replacing the soul architecture with digital population inserts.',
          isCorrect: false,
          rationale:
            'Artificial entities exist, but the custodial strategy for true souls focuses on inversion rather than replacement.'
        },
        {
          text: 'By instituting inversion strategies that weaponize, subvert, and hijack the traits.',
          isCorrect: true,
          rationale:
            'Custodial parasites could not erase these innate firmwares from true soul architecture, so they instituted inversion strategies.'
        }
      ]
    },
    {
      number: 11,
      question: 'Where does the complete Oversoul reside while its avatar is incarnated on Earth?',
      hint: "This location provides a secure, high-density anchor for the soul's complete luminosity.",
      options: [
        {
          text: 'Within the core of the planetary grid to maintain legal presence.',
          isCorrect: false,
          rationale: 'Mission insertion provides presence, but the Oversoul itself is anchored in a high-density Arc Pod.'
        },
        {
          text: 'In a digital data bank maintained by the Aktun production facilities.',
          isCorrect: false,
          rationale:
            'The Aktun lines are for vessel production; the Oversoul resides in a spiritual/technological Arc Pod.'
        },
        {
          text: 'In an Arc Pod container located on a bioship in the atmospheric overlays.',
          isCorrect: true,
          rationale:
            'The complete Oversoul remains anchored within an Arc Pod container located on living bioships situated in the upper atmospheric overlays.'
        },
        {
          text: 'Within the complex neural pathways of the 3rd-density physical brain.',
          isCorrect: false,
          rationale: 'The brain is only an interface; it does not house the complete volume of the Oversoul.'
        }
      ]
    },
    {
      number: 12,
      question: 'What defines the physical process of Facial Morphogenesis in true soul-bearing humans?',
      hint: 'This process suggests that physical appearance is a reflection of the underlying energetic software.',
      options: [
        {
          text: 'The surgical modification performed by custodial entities during resets.',
          isCorrect: false,
          rationale: 'While custodians modified the overall template, individual facial structure is a soul-driven process.'
        },
        {
          text: 'The environmental adaptations required for survival in lower-density fields.',
          isCorrect: false,
          rationale: 'Morphogenesis is driven by internal soul software rather than external environmental pressures.'
        },
        {
          text: "The sculpting of the face by the soul's specific vibrational architecture over time.",
          isCorrect: true,
          rationale:
            "The soul's unique energetic signature sculpts the physical face to resemble its original, un-downgraded ET template."
        },
        {
          text: 'The random recombination of genetic material from parental ancestors.',
          isCorrect: false,
          rationale:
            'While genetics play a role, facial structure is primarily software-specific and determined by the soul.'
        }
      ]
    },
    {
      number: 13,
      question: 'How are non-player entities (NPCs) animated within the physical matrix rendering?',
      hint: 'Consider how a small number of true souls might support a larger group of artificial entities.',
      options: [
        {
          text: 'They possess a unique, low-density soul template created by the Proximal Sols.',
          isCorrect: false,
          rationale: 'Only four thousand true soul templates were created; NPCs lack independent soul structures.'
        },
        {
          text: 'They generate their own internal light through advanced genetic engineering.',
          isCorrect: false,
          rationale:
            'Artificial entities lack immortal connection to Source and cannot generate their own spiritual luminosity.'
        },
        {
          text: 'They draw upon a fraction of light shared by true soul architectures.',
          isCorrect: true,
          rationale:
            'A fraction of light from true souls is temporarily allocated to power their basic biological functions.'
        },
        {
          text: 'They are powered by the electromagnetic energy of the planetary core.',
          isCorrect: false,
          rationale: 'They specifically require the spiritual luminosity of true souls to function within the simulation.'
        }
      ]
    },
    {
      number: 14,
      question: 'What is the expected outcome of the event known as the Homecoming Reunion?',
      hint: 'This event is often referred to as the "Wizard of Oz" moment where masks are removed.',
      options: [
        {
          text: 'The instantaneous recognition of soul family members "out of costume."',
          isCorrect: true,
          rationale:
            'Avatars will immediately recognize surrounding individuals as their true soul family members "out of costume".'
        },
        {
          text: 'The replacement of all physical bodies with high-density holographic sleeves.',
          isCorrect: false,
          rationale:
            'The reunion involves seeing through current forms to true spiritual templates, not receiving new holographic sleeves.'
        },
        {
          text: 'The formal signing of a new Sovereign Accord between all planetary entities.',
          isCorrect: false,
          rationale: "The accord is already in place; the reunion is the realization of the mission's completion."
        },
        {
          text: 'The mass migration of humanity to the original 9th-density Taran home world.',
          isCorrect: false,
          rationale: 'The reunion is about recognition and the dropping of overlays, not a physical migration.'
        }
      ]
    },
    {
      number: 15,
      question: 'What is the primary purpose of an Arc Trajectory for an incarnated avatar?',
      hint: 'This sequence is planned thousands of years in advance to ensure strategic mission goals are met.',
      options: [
        {
          text: "To slowly restore the avatar's memory of their previous 18th-density lives.",
          isCorrect: false,
          rationale:
            'Memories remain deactivated under the Clueless Protocol; the trajectory guides the avatar without conscious memory.'
        },
        {
          text: 'To guide the avatar to precise coordinates required for grid activation.',
          isCorrect: true,
          rationale:
            'True soul avatars are naturally steered to precise geographic and temporal nodes required for grid activation.'
        },
        {
          text: 'To allow the avatar to explore various random experiences across the galaxy.',
          isCorrect: false,
          rationale: 'The trajectory is a meticulously pre-mapped sequence rather than a random exploration.'
        },
        {
          text: 'To accumulate enough biological data to upgrade the modern human template.',
          isCorrect: false,
          rationale: 'The purpose is grid activation and mission fulfillment, not data collection for biological upgrades.'
        }
      ]
    },
    {
      number: 16,
      question: 'Which density is associated with the original Taran Vessel and its aetheric mechanics?',
      hint: 'The original Taran body was significantly more advanced and taller than modern 3rd-density humans.',
      options: [
        {
          text: 'The 18th-density realm of Initial Intelligence.',
          isCorrect: false,
          rationale:
            'The 18th density is where soul architecture originated, but the Taran body was a 9th-density construct.'
        },
        {
          text: 'The 9th-density level of the Aktun production lines.',
          isCorrect: true,
          rationale:
            'The original Taran Vessel was a 9th-density biological masterpiece fully aligned with high-density aetheric mechanics.'
        },
        {
          text: 'The 12th-density realm of the Proximal Sols.',
          isCorrect: false,
          rationale:
            'While the Proximal Sols are high-density, the specific Taran vessel is identified with the 9th density.'
        },
        {
          text: 'The 3rd-density level of modern physical manifestation.',
          isCorrect: false,
          rationale: 'Modern humans are a downgraded 3rd-density version of the original template.'
        }
      ]
    },
    {
      number: 17,
      question: 'What happened to the Taran biological template following historical planetary resets?',
      hint: 'Consider the reduction in cranial capacity and the closing off of vital brain regions.',
      options: [
        {
          text: 'It was upgraded to allow for better survival in lower-density environments.',
          isCorrect: false,
          rationale: 'The changes were a downsizing and restriction of capacity, not an upgrade for better function.'
        },
        {
          text: 'It was systematically downgraded into smaller, slower, and shorter-lived vessels.',
          isCorrect: true,
          rationale:
            'Custodial control structures systematically downgraded the Taran biological template through genetic modification, and modern bodies were downsized into smaller, slower, and shorter-lived vessels.'
        },
        {
          text: 'It was integrated with non-player entities to stabilize the planetary grid.',
          isCorrect: false,
          rationale: 'The downgrading was a custodial tactic to control true souls, not an integration with NPCs.'
        },
        {
          text: 'It was completely replaced by digital inserts and holographic sleeves.',
          isCorrect: false,
          rationale:
            'The original blueprint remains as the core DNA, even if the physical manifestation is downgraded.'
        }
      ]
    },
    {
      number: 18,
      question: 'How many individual lifetimes does an average Arc Trajectory cover across its pre-mapped sequence?',
      hint: 'The total number of lives is quite high, with each life averaging about 35 years.',
      options: [
        {
          text: 'More than 5,000 individual lifetimes averaging 35 years each.',
          isCorrect: true,
          rationale:
            'These trajectories guide the avatar across more than 5,000 individual lifetimes averaging 35 years each.'
        },
        {
          text: 'Approximately twelve lifetimes for each of the Proximal Sols.',
          isCorrect: false,
          rationale:
            'The Proximal Sols are the creators; the trajectories apply to the 4,000 architectures across thousands of lives.'
        },
        {
          text: 'Exactly one hundred lifetimes shared with soul family members.',
          isCorrect: false,
          rationale: 'One hundred refers to the number of souls in a pod cluster, not the number of lifetimes.'
        },
        {
          text: 'Forty-eight lifetimes per every one thousand years of history.',
          isCorrect: false,
          rationale: 'The total count is over 5,000 lifetimes, not a forty-eight-per-millennium schedule.'
        }
      ]
    },
    {
      number: 19,
      question: 'What does the trait of Altruism represent within the Fifteen Attributes of true Soul Architecture?',
      hint: 'This trait involves helping others without looking for a return on the effort.',
      options: [
        {
          text: 'The ability to mentally manipulate spatial data to help others in need.',
          isCorrect: false,
          rationale: 'This describes spatial working memory rather than the behavioral trait of altruism.'
        },
        {
          text: 'Unconditional cooperation and helping behavior without expectation of reward.',
          isCorrect: true,
          rationale:
            'Altruism is unconditional cooperation and helping behavior performed without expectation of reward.'
        },
        {
          text: 'The capacity to analyze the emotional states of others to provide aid.',
          isCorrect: false,
          rationale: 'While related, this more accurately describes empathy or Theory of Mind.'
        },
        {
          text: 'The strategic cooperation with other beings to ensure personal survival.',
          isCorrect: false,
          rationale: 'Altruism is defined as helping without expectation of reward, rather than for personal gain.'
        }
      ]
    },
    {
      number: 20,
      question: 'What is the relationship between the Oversoul and the avatar in terms of spiritual luminosity?',
      hint: 'Think of the avatar as a smaller extension of the larger, uncompressed consciousness.',
      options: [
        {
          text: "The avatar contains the entire volume of the soul's luminosity at birth.",
          isCorrect: false,
          rationale: "The avatar only receives a small projected fraction of the Oversoul's total luminosity."
        },
        {
          text: 'The avatar generates luminosity that is then stored by the Oversoul.',
          isCorrect: false,
          rationale: 'Luminosity originates from the Oversoul and is projected down, not the other way around.'
        },
        {
          text: 'The Oversoul projects a small fraction of its total luminosity into the avatar.',
          isCorrect: true,
          rationale:
            'The Oversoul projects only a small fraction of its total spiritual luminosity into the 3rd-density physical vessel.'
        },
        {
          text: 'The luminosity is shared equally between the avatar and artificial entities.',
          isCorrect: false,
          rationale:
            'Luminosity belongs to the true soul, though a fraction may be temporarily allocated to animate NPCs.'
        }
      ]
    },
    {
      number: 21,
      question: 'True or False: Soul Architecture is dependent on biological evolution to emerge in reality.',
      hint: 'Remember the sequence of cosmic events regarding intelligence and physical matter.',
      options: [
        {
          text: 'True',
          isCorrect: false,
          rationale:
            'Soul Architecture is independent of biological hardware and existed billions of years before physical matter.'
        },
        {
          text: 'False',
          isCorrect: true,
          rationale:
            'Intelligence preceded physicality; soul templates were created by Source Creation before any biological vessel existed.'
        }
      ]
    },
    {
      number: 22,
      question: 'What is the consequence of the dissipation of artificial electromagnetic overlays?',
      hint: 'This event triggers the collapse of lower-density inversions and harmonic restoration.',
      options: [
        {
          text: 'The immediate destruction of the physical Taran biological archetype.',
          isCorrect: false,
          rationale:
            'The biological template is a vehicle; the dropping of overlays restores its potential rather than destroying it.'
        },
        {
          text: 'The automatic re-alignment of avatars with their high-density templates.',
          isCorrect: true,
          rationale:
            'Upon the dissipation of artificial electromagnetic overlays, incarnated avatars will automatically re-align with their high-density templates, collapsing lower-density inversions and restoring harmonic field function.'
        },
        {
          text: 'The activation of a new Clueless Protocol to protect the planetary grid.',
          isCorrect: false,
          rationale: 'The dropping of overlays is the end of the Clueless Protocol, not the start of a new one.'
        },
        {
          text: 'The permanent loss of all memories stored within the 3rd-density avatar.',
          isCorrect: false,
          rationale: 'The dissolution of overlays actually restores memory and true alignment.'
        }
      ]
    },
    {
      number: 23,
      question: 'How many unique soul architectures were formulated by the Proximal Sols from their foundational blueprint?',
      hint: 'This group forms the master template for all ancient starseed extensions.',
      options: [
        {
          text: 'One hundred templates for each of the fifteen firmware attributes.',
          isCorrect: false,
          rationale: 'The total number of unique soul architectures is specifically cited as four thousand.'
        },
        {
          text: 'Five thousand individual extensions for each starseed lineage.',
          isCorrect: false,
          rationale:
            'Five thousand refers to the number of lifetimes in an Arc Trajectory, not the number of soul templates.'
        },
        {
          text: 'Four thousand unique soul architectures to anchor divine consciousness across lower physical realms.',
          isCorrect: true,
          rationale:
            'Exactly four thousand unique soul architectures were formulated to anchor divine consciousness across lower physical realms.'
        },
        {
          text: 'Twelve original templates representing the six seed pairs.',
          isCorrect: false,
          rationale:
            'Twelve is the count of the Proximal Sols themselves, not the total number of soul templates they created.'
        }
      ]
    },
    {
      number: 24,
      question:
        'True or False: Artificial population inserts like NPCs maintain an immortal connection to Source Creation.',
      hint: 'Consider the source of light used to animate these entities within the simulation.',
      options: [
        {
          text: 'True',
          isCorrect: false,
          rationale:
            'Only true soul architectures maintain an immortal connection to Source; artificial entities lack this structure.'
        },
        {
          text: 'False',
          isCorrect: true,
          rationale:
            'Artificial entities rely on borrowed environmental light or automated data streams rather than an immortal connection to Source Creation.'
        }
      ]
    },
    {
      number: 25,
      question: 'What happens to the "borrowed light" when an artificial entity dies?',
      hint: 'This light is only temporarily allocated to animate basic biological functions.',
      options: [
        {
          text: 'It is permanently dissipated into the lower-density planetary field.',
          isCorrect: false,
          rationale: 'The light is not lost but returns to its original source.'
        },
        {
          text: 'It is absorbed by the custodial control structures to power their systems.',
          isCorrect: false,
          rationale:
            'The light belongs to the true soul collective and returns there after the death of artificial entities.'
        },
        {
          text: 'It is archived within the Arc Pods to be reused for future Mission Insertions.',
          isCorrect: false,
          rationale:
            'The light is a shared fraction of luminosity that returns to the collective pool, not specifically the Arc Pod archives.'
        },
        {
          text: 'It detaches and returns to the collective pool of true soul luminosity.',
          isCorrect: true,
          rationale:
            'Upon the death of artificial entities, this borrowed light detaches and returns to the collective pool of true soul luminosity.'
        }
      ]
    }
  ]
};
